"""Roll up the status of every child repo into the hub's STATUS.md."""
from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class PhaseProgress:
    name: str
    done: int
    total: int


def parse_roadmap(text: str) -> list[PhaseProgress]:
    """Parse a ROADMAP.md into per-phase checkbox progress.

    A phase starts at a `## ` heading; items are `- [ ]` / `- [x]` lines.
    Items before any heading accrue to a synthetic "General" phase.
    Phases with no checkbox items are dropped.
    """
    phases: list[PhaseProgress] = []
    current: PhaseProgress | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("## "):
            current = PhaseProgress(name=line[3:].strip(), done=0, total=0)
            phases.append(current)
            continue
        if line.startswith("- [") and len(line) >= 5 and line[4] == "]":
            if current is None:
                current = PhaseProgress(name="General", done=0, total=0)
                phases.append(current)
            current.total += 1
            if line[3].lower() == "x":
                current.done += 1
    return [p for p in phases if p.total > 0]


@dataclass
class RepoStatus:
    name: str
    phases: list[PhaseProgress] = field(default_factory=list)
    last_commit: str = "(no commits)"
    branch: str = "(unknown)"

    @property
    def done(self) -> int:
        return sum(p.done for p in self.phases)

    @property
    def total(self) -> int:
        return sum(p.total for p in self.phases)

    @property
    def pct(self) -> int:
        return round(100 * self.done / self.total) if self.total else 0


def render_status(repos: list[RepoStatus], generated_at: str) -> str:
    """Render the given repo statuses as a single markdown table."""
    lines = [
        "# STATUS",
        "",
        f"> Generated by `operational/snapshot.py` at {generated_at}. Do not edit by hand.",
        "",
        "| Repo | Progress | Last activity | Branch |",
        "| --- | --- | --- | --- |",
    ]
    for r in sorted(repos, key=lambda r: r.name):
        progress = f"{r.pct}% ({r.done}/{r.total})" if r.total else "—"
        lines.append(f"| {r.name} | {progress} | {r.last_commit} | {r.branch} |")
    lines.append("")
    return "\n".join(lines)


def _git(repo: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        check=False,
    )
    return out.stdout.strip()


def read_repo(path: Path) -> RepoStatus:
    status = RepoStatus(name=path.name)
    roadmap = path / "ROADMAP.md"
    if roadmap.exists():
        status.phases = parse_roadmap(roadmap.read_text(encoding="utf-8"))
    last = _git(path, "log", "-1", "--format=%h %ad %s", "--date=short")
    if last:
        status.last_commit = last
    branch = _git(path, "rev-parse", "--abbrev-ref", "HEAD")
    if branch:
        status.branch = branch
    return status


def discover_repos(hub_root: Path) -> list[Path]:
    """Return immediate child directories that are git repos, sorted by name."""
    return sorted(
        p for p in hub_root.iterdir() if p.is_dir() and (p / ".git").exists()
    )


def main() -> None:
    hub_root = Path(__file__).resolve().parent.parent
    repos = [read_repo(p) for p in discover_repos(hub_root)]
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    (hub_root / "STATUS.md").write_text(render_status(repos, generated_at))
    print(f"Wrote STATUS.md for {len(repos)} repo(s).")


if __name__ == "__main__":
    main()
